name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    name: Label when approved
    runs-on: ubuntu-latest
    
    steps:
    - name: Automate approvals
      uses: pullreminders/label-when-approved-action@master
      env: 
        APPROVALS: "1"
        GITHUB_TOKEN: "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"
        ADD_LABEL: "approved"
